services:
  focus-app:
    build: .
    networks:
      - apache_letsencrypt
    ports:
      - "3000:3000"
    volumes:
      - ./notes.md:/app/notes.md
      - ./config.json:/app/config.json
    restart: unless-stopped

networks:
  apache_letsencrypt:
    external: true
